2019-02-25 15:44:52,819 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-25 16:08:34,708 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-25 18:50:30,276 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-25 19:11:39,102 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-25 19:11:51,664 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-25 19:14:34,636 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-25 19:16:09,852 INFO: Microblog startup [in /home/sanbharath/Desktop/project/microblog/app/__init__.py:43]
2019-02-27 23:10:04,940 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-01 00:56:14,028 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-01 00:57:25,889 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-01 00:57:38,637 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-01 01:07:20,296 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-01 01:07:40,435 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-01 12:31:44,648 INFO: Microblog startup [in app/__init__.py:52]
2019-03-01 12:42:58,596 INFO: Microblog startup [in /home/sanbharath/Desktop/SIH/microblog2/app/__init__.py:52]
2019-03-02 20:34:01,444 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-02 22:01:44,115 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-02 22:02:48,787 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 08:41:55,324 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 08:45:48,653 ERROR: Exception on /index [POST] [in c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\flask_login\utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\routes.py", line 35, in index
    language=language)
  File "<string>", line 4, in __init__
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\sqlalchemy\orm\state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\siddharth\downloads\futurein-master\futurein\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 657, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'language' is an invalid keyword argument for Post
2019-03-03 08:55:09,246 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 08:59:03,261 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 09:01:40,929 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 09:02:53,919 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 09:07:00,139 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 09:10:18,466 INFO: Microblog startup [in C:\Users\Siddharth\Downloads\FutureIn-master\futurein\FutureIn\app\__init__.py:52]
2019-03-03 10:07:47,198 INFO: Microblog startup [in /home/siddharth/Desktop/FutureIn/app/__init__.py:52]
